language: ruby
rvm:
- 2.1

before_script:
 - chmod +x ./script/cibuild # 또는 로컬에서 직접 실행 후 커밋

# bundler 를 사용한다고 가정함. 따라서
# `install` 단계에 `bundle install` 이 디폴트로 실행됨.
script: ./script/cibuild

# 브랜치 화이트리스트. GitHub Pages 에서만 사용됨
branches:
  only:
   - source
#  - gh-pages     # gh-pages 브랜치를 테스트 함
#  - /pages-(.*)/ # "pages-" 로 시작하는 모든 브랜치를 테스트 함

sudo : false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # html-proofer 의 설치 속도를 높여줌


after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git config user.name sm1ee
    git config user.email tmdaud100@gmail.com
    git commit -am 'Automatic Update From Travis CI'
    git checkout -b master
    git filter-branch --subdirectory-filter _site/ -f
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -fq https://$GITHUB_API_KEY@github.com/sm1ee/sm1ee.github.io.git master 
  fi

