#!/usr/bin/env bash
set -e # 에러 발생 시 스크립트 중단

bundle exec jekyll build
git checkout source
git branch -D master
git checkout -b master
git filter-branch --subdirectory-filter _site/ -f
git push --all
git checkout source

bundle exec htmlproofer ./_site

